name: vitask
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  http: ^0.12.0+4
  modal_progress_hud: ^0.1.3
  sembast: ^1.9.2
  path_provider: ^1.6.7
  pie_chart: ^3.1.1
  flutter_circular_chart: ^0.1.0
  font_awesome_flutter: ^8.7.0
  flutter_local_notifications: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/